version: "3.7"

services:
    postgres:
        container_name: db
        image: postgres:10.5
        environment:
            - POSTGRES_DB = ${DB_NAME}
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        ports:
            - "5432:5432"
        volumes:
            - .:/usr/src/app
