version: "3.7"

services:
    postgres:
        container_name: db
        image: postgres:10.5
        environment:
            - POSTGRES_DB=${PGDATABASE}
            - POSTGRES_USER=${PGUSER}
            - POSTGRES_PASSWORD=${PGPASSWORD}
        ports:
            - "5432:5432"
        volumes:
            - .:/usr/src/app
    redis:
        image: redis:6.2-alpine
        ports:
            - "6379:6379"
        environment:
            - REDIS_PASSWORD={REDISPASSWORD}
            - REDIS_HOST={REDISHOST}
            - REDIS_PORT={REDISPORT}
