version: "3.7"

services:
    postgres:
        image: postgres:10.5
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_DB = ${DB_NAME}
            - POSTGRES_USERNAME = ${DB_USERNAME}
            - POSTGRES_PASSWORD = ${DB_PASSWORD}
        volumes:
            - .:/usr/src/app
